task/scannerTask.go
Sample "cri-containerd.apparmor.d"
..............................
... suppress ptrace denials when using 'docker ps' or using 'ps' inside a container ...
ptrace (trace,read) peer=cri-containerd.apparmor.d
..............................
=> Issue 117: conatinerd's apparmor profile (on some versions) might block "/proc/<pid>/" read access for non-privileged pods.

cvetools/cvesearch.go, cvetools/tools.go, go.mod, go.sum, vendor/github.com/neuvector/neuvector/controller/api/apis.go, vendor/github.com/neuvector/neuvector/share/cluster/grpc.go, vendor/github.com/neuvector/neuvector/share/container/docker.go, vendor/github.com/neuvector/neuvector/share/global/global.go, vendor/github.com/neuvector/neuvector/share/osutil/file_linux.go, vendor/github.com/neuvector/neuvector/share/osutil/process_linux.go, vendor/github.com/neuvector/neuvector/share/scan/compliance.go, vendor/github.com/neuvector/neuvector/share/scan/scan_report.go, vendor/github.com/neuvector/neuvector/share/scan/scan_utils.go, vendor/github.com/neuvector/neuvector/share/system/cgroup_linux.go, vendor/github.com/neuvector/neuvector/share/system/system_linux.go, vendor/github.com/neuvector/neuvector/share/utils/utils.go, vendor/modules.txt
(1) Synchronized vender: github.com/neuvector/neuvector @ 847c3fced01c4aec1290e252544d0ca9d707b240 (branch 5.0.0)
(2) Implement wipe-out attributes during reconstructing images. 
We usually reconstruct an image from the "docker save" tars with "addition" and "overlay" methods. However, it did include a "deduction" method as well. Thus, we might have false-positive cases for the "whole-image" scan.
Target:
(a) deleted folders will not be included in the whole REPO/Registry scans
(b) However, they will be included when we make the individual "layer" scans.
=> NV6487: Scanner: implement wipe-out attributes during reconstructing image repo

cvetools/cvesearch.go, cvetools/cvetools_test.go
The oracle namespace was being translated as ol:x.y when the format for our mapping is oracle:x. This caused an issue where the oracle was not properly checked for vulnerabilities.
=> NVSHAS-6806 oracle namespace improperly translated.

vendor/github.com/neuvector/neuvector/share/scan/apps.go
Fixes an issue where vendorId and title can be malformatted during jar parsing.
=> NVSHAS-6653, fix for package names during jar parsing.

detectors/feature/rpm/rpm.go
Add support for rhel:9.x to cpe set for rpm scanning.
=> NVSHAS-7765 add rhel 9 to cpe set

cvetools/cvesearch.go, cvetools/sigstore.go
Uses the new `--proxy-url` command line argument when executing the sigstore-interface binary with a proxy url in the request.
=> NVSHAS-7882: add proxy url to sigstore interface execution

server.go
Extending the timeout while registering a new database at controllers.
=> NVSHAS-8340: unexpected scannerRegister lock error in controller

server.go
Fix the nil results from the scanner side. Adding a positive scan-in-progress condition into the next scan queue.
`grpc: server failed to encode response: rpc error: code = Internal desc = grpc: error while marshaling: proto: Marshal called with nil`
=> NVSHAS-8304: Scans failing on one Node only

common/db.go
unhandled collision case sometimes caused map entry to be overwritten and cause inconsistent results when handling jar based modules.
=> NVSHAS-8559 fixed inconsistent jar results

common/common.go, cvetools/cvesearch.go, cvetools/image.go, cvetools/scan_cache.go, cvetools/types.go, monitor/monitor.c, scanner.go, server.go, standalone.go, task/scannerTask.go, tasker.go
Two configurable environment variables:
```
env:
- name: MAX_CACHE_RAW_MB                            Base OS cache
value: "500"                                                        <== default: "0" MB (disabled)
- name: MAX_CACHE_RECORD_MB                     Scanned record cache
value: "512"                                                        <== default: "1000" MB
```
The two tiers of caches.
- base OS image layer data (compressed raw data files).
- scanned records, including secret scans, file maps, and layer package data (zipped JSON files).
-
About 50-70% of the scanning time could be shortened if the "repeated" layer scannings (or different databases) or same base OS images often occur.
Note: For the critical section among the multiple scannerTasks instances, the (Unix) …
=> NVSHAS-7664: Help reduce ISP data charges when performing registry scanning

common/common.go
Add values for new ubuntu and debian releases.
=> NVSHAS-8675 add support for new ubuntu and debian release mapping

cvetools/cvesearch.go
amazon linux no longer has only two versions.
=> NVSHAS-8842 support for more amazon linux versions

cvetools/cvesearch.go, scanner.go, task/scannerTask.go
(1) Avoid the top layer of the image working folder, "/tmp/image", which is removed when the new scanner is up.
(2) Make the scanner cache is default disabled.
=> NVSHAS-8907:  Scan cache (hostPath) clears up when one of the multiple scanner gets deleted

cvetools/cvesearch.go, cvetools/image.go, cvetools/scan_cache.go, cvetools/tools.go
(1) correct the layer sequences from the image scans.
(2) REPO: replace the correct layer mapping from the image history. The (history size == 0) might have the tar layer data.
(3) Ignore the cacher's lock error messages on a PVC setup.
=> Scanner cache: correct the layer orders for registry and repository scans

cvetools/image.go
The REPO OCI format is allowed to reuse the same layerID to layers on docker v25 platform.
=> NVSHAS-8949: goroutine crash at cvetools.getImageLayers()

cvetools/image.go
Add R-language module parser from their manifest files.
Sample:
```
{
"Name": "base",  
"Version": "4.0.5",
"Source": "r"
},
```
=> NVSHAS-8995: add R-lang module parser

task/scannerTask.go
Add a new initialization at scannerTask instance.
=> NVSHAS-9015: goroutine crash at cvetools.(*ScanTools).DetectAppVul()

cvetools/cvesearch.go, cvetools/image.go, cvetools/types.go, server.go, standalone.go, task/scannerTask.go
(1) Update dotNet package parser
(2) Remove the duplicated restrictions to produce module/cve entries if they are not from the same file
(3) Cacher correctness: local scans, the docker history was wrong or missing an entry. It causes the base-layer was not included.
(4) Debug purpose: add the module output from the front-end results.
=> NVSHAS-9026: dup and missing .NET module name

monitor/monitor.c, scanner.go, server.go
1. Add HealthCheck grpc call to check controller health periodically, if the controller is down, we restart the re-register loop
2. user is able to customize the period and retry max
1. old scanner > old controller, Expected cause the scanner is unable to register the controller again, since no logic for scanner to re-register
2. old scanner > new controller, Expected cause the scanner is unable to register the controller again, since no logic for scanner to re-register
3. new scanner > old controller, Expected cause the scanner is unable to register the controller again
4. new scanner > new controller, resolve the problem
=> [NVSHAS-9189] Scan will stuck in scheduling after controller is shutdown and restarted

monitor/monitor.c
When the pipe connecting container runtime, monitor and scanner's stdout disconnected, scanner will crash due to broken pipe signal.
However, monitor doesn't write to stdout if debug is disabled, so it has no chance to get restarted at the same time.
Therefore, new scanners keep crashing due to Broken pipe errors.
This commit makes monitor write information to stdout after each time scanner restart.  This way monitor has chance to automatically recover if the pipe disconnects.
=> fix: NVSHAS-9423 handle sigpipe properly

scanner.go
For standalone scanner, it doesn't need to reload internal certificate.  Reloading certificate would lead to error during standalone scan when UID/GID is not 0. 
Verified both standalone and k8s scenario.
=> fix: NVSHAS-9523 standalone scanner issue

monitor/monitor.c
Allow users to specify a new env var, SCANNER_DEBUG_MODE, to enable the debug mode in scanner.
=> fix: NVSHAS-9628 provide SCANNER_DEBUG_MODE env for debugging

server.go
- Main issue is db too large, thus we need more time to write, increase time out from 60 to 180 seconds
=> [NVSHAS-9681] Scanner register to controller timeout issue

.github/workflows/release.yml
In the previous version, rancher DockerHub's v6 tag is not updated.  This PR fixes the issue.
Ideally we should move the v6 step to another job.  I will do that in another PR.
=> fix: publish to rancher nv scanner v6

package/Dockerfile
The permission is not ported to SLSA build correctly.
=> fix: permission issues on OpenShift scanner

.github/workflows/golangci-lint.yml
1.24 is causing issues in lint. This is a temporary fix to re-enable golangci-lint.
=> chore: pin golang version used in lint
