Makefile
This reverts commit 8aac903a19e01804786c5bbc4abc73640a172e71.
=> Revert "Build scanner with network turned off"

go.mod, go.sum, vendor/github.com/neuvector/neuvector/controller/api/apis.go, vendor/github.com/neuvector/neuvector/controller/api/apis.yaml, vendor/github.com/neuvector/neuvector/share/clus_apis.go, vendor/github.com/neuvector/neuvector/share/container/containerd.go, vendor/github.com/neuvector/neuvector/share/scan/apps.go, vendor/modules.txt
The pom.xml has all required dependent JARs information. In the customer's case, we can not find its dependent JARs in this image. Thus, this JAR could not run, either. It might be a mistake for the image developer to put this JAR in this image.
As a result, we will not rely on pom.xml in the future.
=> NV6208, NV5079: reducing false positive CVE cases on java applications.

go.mod, go.sum, vendor/github.com/neuvector/neuvector/controller/api/apis.go, vendor/github.com/neuvector/neuvector/share/orchestration/docker.go, vendor/github.com/neuvector/neuvector/share/orchestration/ecs.go, vendor/github.com/neuvector/neuvector/share/orchestration/kubernetes.go, vendor/github.com/neuvector/neuvector/share/orchestration/noop.go, vendor/github.com/neuvector/neuvector/share/orchestration/rancher.go, vendor/github.com/neuvector/neuvector/share/orchestration/types.go, vendor/github.com/neuvector/neuvector/share/orchestration/unknown.go, vendor/github.com/neuvector/neuvector/share/scan/apps.go, vendor/github.com/neuvector/neuvector/share/scan/scan_utils.go, vendor/modules.txt
scan inner "jar" files within a "war" file.
=> scanner: support WAR's inner jar files scan

cvetools/apps.go
Adds exception so that log4j components are also compared against the base log4j entry.
=> NVSHAS-6331 fix to support exception for log4j components.

cvetools/cvesearch.go
(1) the container scan results. include the complete module list
(2) Combined with neuvector PR#258
=> NV6435: Add modules for container scan

cvetools/tools.go
Those missing "set-perm" items are all folders. The file map has mishandled the folder entries.
=> NV6521: the compliance report for test number I.4.8 in registry scan is missing.

cvetools/cvesearch.go
Due to database data structure limitations scanner needed the ability to override certain CVEs with incomplete or incorrect data from the source. Included are overrides for CVE-2019-13509, CVE-2021-21284 and CVE-2021-21285 for centos:7.
=> NVSHAS-6281 added scanner side manual override for version vulnerabilities

cvetools/cvesearch.go, cvetools/sigstore.go
=> Revert "NVSHAS-7882: add proxy url to sigstore interface execution"

cvetools/cvesearch.go, cvetools/sigstore.go
This PR requires the following PR (https://github.com/neuvector/sigstore-interface/pull/11) to be merged at the same time.
=> NVSHAS-7882: pass sigstore proxy credentials through stdin

common/db.go, cvetools/cvesearch.go
Added support for photon to db.go and cvesearch.go
=> NVSHAS-7824 add support for photon os and namespaces

go.mod, go.sum, vendor/github.com/neuvector/neuvector/share/scan/apps.go, vendor/github.com/neuvector/neuvector/share/scan/scan_utils.go, vendor/modules.txt
Sync with neuvector share to add php composer support to scanner.
=> NVSHAS-6483 sync with to add php composer support.

cvetools/scan_cache.go
```
const curVersion = 0
const versionDescription = "initial implementation"
```
=> Scan cacher: add cache's invalidation feature

go.mod, go.sum, vendor/github.com/neuvector/neuvector/share/scan/apps.go, vendor/github.com/neuvector/neuvector/share/scan/compliance.go, vendor/github.com/neuvector/neuvector/share/scan/registry/tokentransport.go, vendor/github.com/neuvector/neuvector/share/scan/scan_report.go, vendor/modules.txt
sync with neuvector share to include fix for php parsing.
=> NVSHAS-6483 sync with neuvector share

common/db.go, cvetools/apps.go
(1) Remove duplicate CVE entry per module
(2) Make the consistent app's vul map which the map size was random by the map iterations (affecting detected VUL counts)
=> NVSHAS-9022, NVSHAS-9031: duplicate module entries by a JAR file

standalone.go
Add "library/" or username prefix on repository when scanning
=> [NVSHAS-9009]  Add "library/" or username prefix on repository when scanning

common/db.go, cvetools/cvesearch.go
Add support to use new tumbleweed db entries.
=> NVSHAS-9070 add support for open suse tumbleweed

cvetools/cvesearch.go, detectors/namespace.go
scanner side support for suse liberty.
=> NVSHAS-8674 add support for suse liberty.

go.mod, go.sum, scanner.go, vendor/github.com/neuvector/neuvector/controller/api/apis.go, vendor/github.com/neuvector/neuvector/controller/api/apis.yaml, vendor/github.com/neuvector/neuvector/controller/api/internal_apis.go, vendor/github.com/neuvector/neuvector/share/k8sutils/k8sutils.go, vendor/github.com/neuvector/neuvector/share/k8sutils/permissions.go, vendor/github.com/neuvector/neuvector/share/migration/migration_informer.go, vendor/modules.txt
Allow scanner to run when RBAC is missing.
=> NVSHAS-9289 allow missing RBAC

go.mod, go.sum, vendor/github.com/neuvector/neuvector/controller/api/apis.go, vendor/github.com/neuvector/neuvector/controller/api/apis.yaml, vendor/github.com/neuvector/neuvector/share/clus_apis.go, vendor/github.com/neuvector/neuvector/share/cluster/intfs.go, vendor/github.com/neuvector/neuvector/share/migration/migration_informer.go, vendor/github.com/neuvector/neuvector/share/orchestration/types.go, vendor/github.com/neuvector/neuvector/share/scan/compliance.go, vendor/modules.txt
Update dependency to adopt a fix in neuvector/neuvector
=> fix: NVSHAS-9335 secret controller not work

cvetools/cvesearch.go
Previously any signature scanning error was silent.
<s>This is a draft so that I can include the `GetImageInfo` changes from this PR (https://github.com/neuvector/neuvector/pull/1526) before merging.</s>
I'm going to create another PR for that since there might be some complications, and to keep this one simple.
=> add logging when signature scan encounters errors

common/db.go, cvetools/cvesearch.go
adds rocky linux OS support for scanner.
=> NVSHAS-8594 add scanner side support for rocky linux

go.mod, go.sum, vendor/github.com/neuvector/neuvector/controller/api/apis.go, vendor/github.com/neuvector/neuvector/controller/api/apis.yaml, vendor/github.com/neuvector/neuvector/controller/api/internal_apis.go, vendor/github.com/neuvector/neuvector/share/clus_apis.go, vendor/github.com/neuvector/neuvector/share/system/cgroup_linux.go, vendor/github.com/neuvector/neuvector/share/utils/version.go, vendor/modules.txt
sync new share to scanner, needed for comparewithoutepoch()
=> NVSHAS-9436 sync share for scanner

cvetools/cvesearch.go, cvetools/cvetools_test.go
Support for certain namespaces that do not contain epoch data to ignore epoch during version comparison.
=> NVSHAS-9436 support for epochless comparison

go.mod, go.sum, vendor/github.com/neuvector/neuvector/share/container/docker.go, vendor/modules.txt
- Sync with NeuVector repo for fixing local scan issue.
=> [NVSHAS-9683] Sync with NeuVector

.github/workflows/golangci-lint.yml, .golangci.yml, common/db.go, cvetools/apps_test.go, cvetools/cvesearch.go, cvetools/cvetools_test.go, cvetools/image.go, cvetools/scan_cache.go, cvetools/tools.go, detectors/osrelease_test.go
Add golangci to neuvector/scanner
Sample PR:
https://github.com/holyspectral/scanner/pull/1/files
=> feat: add golangci for scanner

.gitattributes, .github/workflows/release.yml, .gitignore, Makefile, data/cvedb, package/Dockerfile
Create standalone Dockerfile and GHA to release SLSA builds.
=> feat: NVSHAS-9495 SLSA build

go.mod, go.sum, vendor/github.com/neuvector/neuvector/share/scan/registry/manifest.go, vendor/github.com/vishvananda/netns/.golangci.yml, vendor/github.com/vishvananda/netns/.yamllint.yml, vendor/github.com/vishvananda/netns/netns_linux.go, vendor/github.com/vishvananda/netns/netns_others.go, vendor/modules.txt
- update vendor from neuvector repo
=> [update-vendor] Update neuvector repo 20250204

cvetools/apps.go, cvetools/cvesearch.go
(1) sync with enforcer, targeted on 5.4.4 release
(2) sync with neuvector packages.
=> NV9905: add k8s workload scans

cvetools/cvesearch.go
- Do not comapre the fips version with non-fips version
=> fix: false positive of the oracle
